version: '3.7'

networks:
  local:
    driver: bridge

services:
  cron:
    image: alpine:latest
    container_name: sign-cron-${PROFILE_ENV}
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - CRON_SCHEDULE=${CRON_SCHEDULE}
    volumes:
      - ./docker-entrypoint-cron.d/reset.sql:/reset.sql
      - ./docker-entrypoint-cron.d/reset.sh:/reset.sh
      - /etc/localtime:/etc/localtime:ro
      - ./logs:/var/log
    entrypoint:
      [
        "sh",
        "-c",
        "apk update && apk add --no-cache postgresql-client && chmod 755 /reset.sh && echo '$CRON_SCHEDULE /reset.sh >> /var/log/cron_job.log 2>&1' > /etc/crontabs/root && crond -f"
      ]
    networks:
      - local